# Generated by Django 3.2.8 on 2021-10-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_auto_20211027_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created',)},
        ),
    ]
